FROM golang:1.22.1 AS builder

WORKDIR /app/gophermart

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /gophermart ./cmd/gophermart/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /gophermart /app/gophermart

CMD ["/app/gophermart"]
